# Generated by Django 3.2.5 on 2021-08-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210811_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
